/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICryptoDevsNFT__factory } from "./ICryptoDevsNFT__factory";
export { IFakeNFTMarketplace__factory } from "./IFakeNFTMarketplace__factory";
