/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICryptoDevsNFT } from "./ICryptoDevsNFT";
export type { IFakeNFTMarketplace } from "./IFakeNFTMarketplace";
